blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/vulpes-vulpes/batr/discussions
    about: For general questions, usage help, or discussions, please use GitHub Discussions instead
